/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameproject;

/**
 *
 * @author Chiesaafandy
 */
public class Level extends javax.swing.JFrame {

    /**
     * Creates new form Level
     */
    public Level() {
        initComponents();
        setSize(800,600);
        setLocation(200,100);

        setResizable(false);
        MCharacter mc = new MCharacter();

        
        mc.setHP(mc.getMaxHP());
        mc.setDamage(mc.getMaxDamage());
        mc.setHeal(mc.getMaxHeal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        btnBossIce = new javax.swing.JButton();
        btnBossEarth = new javax.swing.JButton();
        MainMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/BossFireBorder.png"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 150, 70, 70);

        btnBossIce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/BossIceBorder.png"))); // NOI18N
        btnBossIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBossIceActionPerformed(evt);
            }
        });
        getContentPane().add(btnBossIce);
        btnBossIce.setBounds(470, 30, 70, 90);

        btnBossEarth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/BossEarthBorder.png"))); // NOI18N
        btnBossEarth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBossEarthMouseEntered(evt);
            }
        });
        btnBossEarth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBossEarthActionPerformed(evt);
            }
        });
        getContentPane().add(btnBossEarth);
        btnBossEarth.setBounds(700, 400, 90, 90);

        MainMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/MapLevel.png"))); // NOI18N
        MainMap.setText("jLabel1");
        getContentPane().add(MainMap);
        MainMap.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBossEarthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBossEarthActionPerformed
        BossEarthFrame bossE = new BossEarthFrame();
        
        bossE.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBossEarthActionPerformed

    private void btnBossEarthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBossEarthMouseEntered
        System.out.println("mouse enter ?");
    }//GEN-LAST:event_btnBossEarthMouseEntered

    private void btnBossIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBossIceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBossIceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainMap;
    private javax.swing.JButton btnBossEarth;
    private javax.swing.JButton btnBossIce;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
