/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameproject;

import javax.swing.JOptionPane;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Chiesaafandy
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setSize(800,600);
        setLocation(200,100);

        setResizable(false);
        
        MCharacter mc = new MCharacter();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnStart = new javax.swing.JButton();
        LbTitle = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        BtnStart.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        BtnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/StartButton.png"))); // NOI18N
        BtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartActionPerformed(evt);
            }
        });
        getContentPane().add(BtnStart);
        BtnStart.setBounds(280, 350, 270, 80);

        LbTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/Title.png"))); // NOI18N
        LbTitle.setToolTipText("");
        getContentPane().add(LbTitle);
        LbTitle.setBounds(10, 80, 776, 87);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameproject/TitleScreen.png"))); // NOI18N
        BackGround.setText("jLabel2");
        getContentPane().add(BackGround);
        BackGround.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartActionPerformed
        MCharacter mc = new MCharacter();

        MainMenu frame = new MainMenu();
        String nama = JOptionPane.showInputDialog(frame, "Insert your name");
        if(nama== null){
        }

        else{

            mc.setName(nama);
            mc.getName();
            
            System.out.println(mc.getName());

            Prologue pembukaan = new Prologue();
            pembukaan.setVisible(true);
            this.dispose();}
    }//GEN-LAST:event_BtnStartActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton BtnStart;
    private javax.swing.JLabel LbTitle;
    // End of variables declaration//GEN-END:variables
}
